---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.go"
  - "**.md"
exclude_paths:
  - config/
  - vendor/
  - node_modules/
  - public/dist/styles/font-awesome.css
  - public/dist/styles/normalize.css
  - src/bindata/bindata.go
