language: go
go:
    - 1.7
    - 1.8
    - 1.9
    - "1.10"
    - tip

matrix:
    allow_failures:
        - go: tip

branches:
    only:
        - master
        - develop

notifications:
    email:
        - lee@keitel.xyz

install: go get -u github.com/jteeuwen/go-bindata/...
script:
    - make bindata
    - make test
