language: go
go:
  - "1.11"
  - tip

matrix:
  allow_failures:
    - go: tip

branches:
  only:
    - master
    - develop

notifications:
  email:
    - lee@keitel.xyz

install: go get -u github.com/go-bindata/go-bindata/...
script:
  - make bindata
  - make test
