version: '3'
services:
    pg-dhcp:
        image: packet-guardian:latest
        container_name: 'pg-dhcp'
        depends_on:
            - pg-database
        links:
            - pg-database
        volumes:
            - ./config-dhcp.toml:/app/packet-guardian/config/config.toml:ro
            - ./dhcp-pools.conf:/app/packet-guardian/config/dhcp.conf:ro
        ports:
            - 67:67
        command: dhcp

    pg-web:
        image: packet-guardian:latest
        container_name: 'pg-web'
        depends_on:
            - pg-database
        links:
            - pg-database
        volumes:
            - ./config-pg.toml:/app/packet-guardian/config/config.toml:ro
        ports:
            - 80:80
            - 443:443
        command: web

    pg-database:
        image: mariadb:latest
        container_name: 'pg-database'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: pg
        command: mysqld --ansi
